name: First Workflow
on: workflow_dispatch
jobs:
  first_job: 
    runs_on: ubuntu_latest
    steps:
      -name: Print greeting
       run: echo "Hello world!"
      -name: Print goodbye
       run: echo "Good bye"
      
